namespace DpmCalculator.Gears.Models

module GearType =
    type GearEnum =
        | Cap = 1
        | FaceAccessory = 2
        | EyeAccessory = 3
        | Earrings = 4
        | Coat = 5
        | LongCoat = 6
        | Pants = 7
        | Shoes = 8
        | Gloves = 9
        | Cape = 10
        | Ring = 11
        | SeedRing = 12
        | Pendant = 13
        | Belt = 14
        | Medal = 15
        | ShoulderPad = 16
        | Pocket = 17
        | Badge = 18
        | Heart = 19
        | Emblem = 20
        | Weapon = 21
        | Katara = 22
        | SubWeapon = 23
        | Title = 24
        | PetEquip = 25
        | DragonMask = 26
        | DragonPendant = 27
        | DragonWings = 28
        | DragonTail = 29
        | MachineEngine = 30
        | MachineArms = 31
        | MachineLegs = 32
        | MachineFrame = 33
        | MachineTransistors = 34
        | All = 35