namespace DpmCalculator.Core.Models

module JobType =
    type JobBranchEnum = 
        | Warrior = 1
        | Magician = 2
        | Bowman = 3
        | Thief = 4
        | Pirate = 5
        | All = 6

    type JobClassEnum =
        | Adventurer = 1
        | Cygnus = 2
        | Resistance = 3
        | Demon = 4
        | Heroes = 5
        | Nova = 6
        | Flora = 7
        | Anima = 8
        | Zero = 9
        | Kinesis = 10
        | All = 11

    type JobEnum =
        | Hero = 1
        | Paladin = 2
        | DarkKnight = 3
        | ArchMageFp = 4
        | ArchMageIl = 5
        | Bishop = 6
        | BowMaster = 7
        | Marksman = 8
        | Pathfinder = 9
        | NightLord = 10
        | Shadower = 11
        | DualBlade = 12
        | Buccaneer = 13
        | Captain = 14
        | Cannoneer = 15
        | DawnWarrior = 16
        | Mihile = 17
        | FlameWizard = 18
        | WindArcher = 19
        | NightWalker = 20
        | ThunderBreaker = 21
        | Blaster = 22
        | BattleMage = 23
        | WildHunter = 24
        | Mechanic = 25
        | Xenon = 26
        | DemonSlayer = 27
        | DemonAvenger = 28
        | Aran = 29
        | Luminous = 30
        | Evan = 31
        | Mercedes = 32
        | Phantom = 33
        | Shade = 34
        | Kaiser = 35
        | Kain = 36
        | Cadena = 37
        | AngelicBuster = 38
        | Adele = 39
        | Illium = 40
        | Ark = 41
        | Lara = 42
        | Hoyoung = 43
        | Zero = 44
        | Kinesis = 45
        | All = 46